# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flightplan' do
  pod 'AppCenter/Crashes', '~> 2.1.0'
  pod 'AppCenter/Analytics', '~> 2.1.0'
  pod 'AppCenterReactNativeShared', '~> 2.1.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flightplan

  

  platform :ios, '9.0'
  target 'flightplanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'flightplan-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for flightplan-tvOS

  target 'flightplan-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
